// Asciidoctor attributes

:toc: left
:sectnums:
:sectnumlevels: 3
:!linkcss:
:source-highlighter: highlightjs
:data-uri:

// custom attributes

:f7: Red Hat Fuse 7

= Fuse 7 persistence quickstarts

`quickstarts/persistence` examples show different aspects of persistence management in {f7}.

This complex topic is divided into several subprojects and examples.

== Persistence manual
`quickstarts/persistence/manual` Maven project is a collection of Asciidoc documents that can be processed into HTML documentation
containing in-depth information about JDBC, JMS, transactions, data source management, configuration etc.

This documentation can be built using:
[listing,options="nowrap"]
----
$ cd persistence/manual
$ mvn clean process-resources
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< org.jboss.fuse.quickstarts:manual >------------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: manual ${project.version}
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
...
[INFO] Rendered */persistence/manual/src/main/asciidoc/index.adoc
----

Final documentation can be found in `persistence/manual/target/generated-docs/index.html`.

== Database and configuration scripts

`persistence/databases` directory contains different scripts and examples which are not itself part of Maven artifact:

* `scripts` contains SQL scripts, referred to from chapter 1 of the manual (_Database configuration_)

* `cm` contains sample Configuration Admin factory configuration that may be used to configure JDBC connection pool
using `pax-jdbc` features

* `blueprints` contains sample Blueprint XML files that may be dropped directly to `$FUSE_HOME/deploy` directory
(after configuring docker-based databases) or used as reference examples for normal OSGi bundles. These blueprints
use _deployment method_ to configure JDBC data sources.

== Message broker and configuration scripts

`persistence/message-brokers` directory contains different examples which are not itself part of Maven artifact:

* `cm` contains sample Configuration Admin factory configuration that may be used to configure JMS connection pool
using `pax-jms` features

* `blueprints` contains sample Blueprint XML files that may be dropped directly to `$FUSE_HOME/deploy` directory
(after configuring docker-based message brokers) or used as reference examples for normal OSGi bundles. These blueprints
use _deployment method_ to configure JMS connection factories.

== Standalone example

`standalone-xa` Maven project contains JUnit tests showing some code-only examples:

* `StandaloneTxManagerTest` shows how to configure Narayana Transaction Manager and use it in canonical JTA example with XA recovery

* `StandaloneXADataAccessTest` shows how DBCP2 connections pools may be configured in Java™ code. This example's
goal is to clear confusion between database-specific and generic instances of `javax.sql.(XA)DataSource` interface implementations.

* `StandaloneWMQ9AccessTest` shows _canonical_ methods for accessing IBM MQ 9 broker. Because IBM MQ drivers are not accessible
via Maven Central repository, code examples use Spring configuration and there's special `wmq9` Maven profile
with `system`-scoped dependency. When running this example, we have to specify a property for the location
of MQ drivers.
+
[listing,options="nowrap"]
----
$ ls -la /data/downloads/ibm.com/IBM\ MQ/9.0.5.0-IBM-MQ-Install-Java-All/JavaSE/
total 12732
drwxrwxr-x. 2 ggrzybek ggrzybek    4096 04-13 16:20 .
drwxrwxr-x. 5 ggrzybek ggrzybek    4096 04-13 16:22 ..
-rw-rw-r--. 1 ggrzybek ggrzybek  775948 04-13 16:20 bcpkix-jdk15on-157.jar
-rw-rw-r--. 1 ggrzybek ggrzybek 3759724 04-13 16:20 bcprov-jdk15on-157.jar
-rw-rw-r--. 1 ggrzybek ggrzybek 8278943 04-13 16:20 com.ibm.mq.allclient.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   43698 04-13 16:20 com.ibm.mq.traceControl.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   22769 04-13 16:20 fscontext.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   58349 04-13 16:20 jms.jar
-rw-rw-r--. 1 ggrzybek ggrzybek   77116 04-13 16:20 providerutil.jar

$ pwd
/home/ggrzybek/sources/github.com/jboss-fuse/karaf-quickstarts/persistence

$ mvn clean test -Pqtest -Pwmq9 -f standalone-xa/ -Dmq9library.path='/data/downloads/ibm.com/IBM MQ/9.0.5.0-IBM-MQ-Install-Java-All/JavaSE' -Dtest=StandaloneWMQ9AccessTest
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< org.jboss.fuse.quickstarts:standalone-xa >--------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: standalone transaction support ${project.version}
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ standalone-xa ---
[INFO] Deleting /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ standalone-xa ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ standalone-xa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ standalone-xa ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jboss.fuse.quickstarts.persistence.standalone.StandaloneWMQ9AccessTest
14:46:42 INFO [AbstractApplicationContext] (AbstractApplicationContext.java:583) : Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5cee5251: startup date [Wed Feb 27 14:46:42 CET 2019]; root of context hierarchy
14:46:42 INFO [XmlBeanDefinitionReader] (XmlBeanDefinitionReader.java:317) : Loading XML bean definitions from class path resource [StandaloneWMQ9AccessTest.xml]
14:46:42 INFO [StandaloneWMQ9AccessTest] (StandaloneWMQ9AccessTest.java:41) : Using WMQ9 queue: com.ibm.mq.jms.MQQueue
14:46:43 INFO [StandaloneWMQ9AccessTest] (StandaloneWMQ9AccessTest.java:58) : MESSAGE: Hello IBM MQ 9
14:46:43 INFO [StandaloneWMQ9AccessTest] (StandaloneWMQ9AccessTest.java:59) : MESSAGE:
  JMSMessage class: jms_text
  JMSType:          null
  JMSDeliveryMode:  2
  JMSDeliveryDelay: 0
  JMSDeliveryTime:  0
  JMSExpiration:    0
  JMSPriority:      4
  JMSMessageID:     ID:414d512046555345514d2020202020208884765c02c74f23
  JMSTimestamp:     1551275202931
  JMSCorrelationID: null
  JMSDestination:   queue:///DEV.QUEUE.1
  JMSReplyTo:       null
  JMSRedelivered:   false
    JMSXAppID: jar
    JMSXDeliveryCount: 1
    JMSXUserID: app
    JMS_IBM_Character_Set: UTF-8
    JMS_IBM_Encoding: 273
    JMS_IBM_Format: MQSTR
    JMS_IBM_MsgType: 8
    JMS_IBM_PutApplType: 28
    JMS_IBM_PutDate: 20190227
    JMS_IBM_PutTime: 13464294
Hello IBM MQ 9
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.17 s - in org.jboss.fuse.quickstarts.persistence.standalone.StandaloneWMQ9AccessTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.103 s
[INFO] Finished at: 2019-02-27T14:46:43+01:00
[INFO] ------------------------------------------------------------------------
----

* `StandaloneArtemisAccessTest` shows _canonical_ methods for accessing A-MQ 7 broker. This example may be run
without specifying any profile (except `-Pqtest`).
+
[listing,options="nowrap"]
----
14:51 $ pwd
/home/ggrzybek/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa

14:51 $ mvn clean test -Pqtest -Dtest=StandaloneArtemisAccessTest,StandaloneXAArtemisAccessTest
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< org.jboss.fuse.quickstarts:standalone-xa >--------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: standalone transaction support 7.3.0.fuse-730008
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ standalone-xa ---
[INFO] Deleting /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ standalone-xa ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ standalone-xa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ standalone-xa ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jboss.fuse.quickstarts.persistence.standalone.StandaloneArtemisAccessTest
14:55:16 INFO [AbstractApplicationContext] (AbstractApplicationContext.java:583) : Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5cee5251: startup date [Wed Feb 27 14:55:16 CET 2019]; root of context hierarchy
14:55:16 INFO [XmlBeanDefinitionReader] (XmlBeanDefinitionReader.java:317) : Loading XML bean definitions from class path resource [StandaloneArtemisAccessTest.xml]
14:55:17 INFO [StandaloneArtemisAccessTest] (StandaloneArtemisAccessTest.java:45) : Using Artemis queue: org.apache.activemq.artemis.jms.client.ActiveMQQueue
14:55:17 INFO [SaslMechanismFinder] (SaslMechanismFinder.java:106) : Best match for SASL auth was: SASL-PLAIN
14:55:17 INFO [JmsConnection] (JmsConnection.java:1325) : Connection ID:2878de25-451f-4532-914c-b33e66d88525:1 connected to remote Broker: amqp://localhost:61616
14:55:17 INFO [StandaloneArtemisAccessTest] (StandaloneArtemisAccessTest.java:60) : Using QPid queue: org.apache.qpid.jms.JmsQueue
14:55:17 INFO [StandaloneArtemisAccessTest] (StandaloneArtemisAccessTest.java:64) : MESSAGE: Hello A-MQ 7
14:55:17 INFO [StandaloneArtemisAccessTest] (StandaloneArtemisAccessTest.java:65) : MESSAGE: JmsTextMessage { org.apache.qpid.jms.provider.amqp.message.AmqpJmsTextMessageFacade@5536379e }
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.304 s - in org.jboss.fuse.quickstarts.persistence.standalone.StandaloneArtemisAccessTest
[INFO] Running org.jboss.fuse.quickstarts.persistence.standalone.StandaloneXAArtemisAccessTest
14:55:17 INFO [JmsPoolXAConnectionFactory] (JmsPoolXAConnectionFactory.java:77) : Porovided ConnectionFactory is JMS 2.0+ capable.
14:55:17 INFO [TransactionStatusManager] (TransactionStatusManager.java:138) : ARJUNA012170: TransactionStatusManager started on port 44603 and host 127.0.0.1 with service com.arjuna.ats.arjuna.recovery.ActionStatusService
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.135 s - in org.jboss.fuse.quickstarts.persistence.standalone.StandaloneXAArtemisAccessTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.380 s
[INFO] Finished at: 2019-02-27T14:55:18+01:00
[INFO] ------------------------------------------------------------------------
----

* `StandaloneAMQ6AccessTest` shows _canonical_ methods for accessing A-MQ 6 broker. This example should be run
with `-Pamq6` Maven profile.
+
[listing,options="nowrap"]
----
14:55 $ mvn clean test -Pqtest -Pamq6 -Dtest=StandaloneAMQ6AccessTest
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< org.jboss.fuse.quickstarts:standalone-xa >--------------
[INFO] Building Red Hat Fuse :: Quickstarts :: persistence :: standalone transaction support 7.3.0.fuse-730008
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ standalone-xa ---
[INFO] Deleting /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ standalone-xa ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ standalone-xa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ standalone-xa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /data/sources/github.com/jboss-fuse/karaf-quickstarts/persistence/standalone-xa/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ standalone-xa ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jboss.fuse.quickstarts.persistence.standalone.StandaloneAMQ6AccessTest
15:45:28 INFO [AbstractApplicationContext] (AbstractApplicationContext.java:583) : Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@60d8c9b7: startup date [Wed Feb 27 15:45:28 CET 2019]; root of context hierarchy
15:45:28 INFO [XmlBeanDefinitionReader] (XmlBeanDefinitionReader.java:317) : Loading XML bean definitions from class path resource [StandaloneAMQ6AccessTest.xml]
15:45:28 INFO [StandaloneAMQ6AccessTest] (StandaloneAMQ6AccessTest.java:45) : Using A-MQ 6 queue: org.apache.activemq.command.ActiveMQQueue
15:45:29 INFO [StandaloneAMQ6AccessTest] (StandaloneAMQ6AccessTest.java:59) : Using A-MQ 6 queue: org.apache.activemq.command.ActiveMQQueue
15:45:29 INFO [StandaloneAMQ6AccessTest] (StandaloneAMQ6AccessTest.java:63) : MESSAGE: Hello A-MQ 6
15:45:29 INFO [StandaloneAMQ6AccessTest] (StandaloneAMQ6AccessTest.java:64) : MESSAGE: ActiveMQTextMessage {commandId = 5, responseRequired = true, messageId = ID:everfree.forest-38313-1551278728748-1:1:1:1:1, originalDestination = null, originalTransactionId = null, producerId = ID:everfree.forest-38313-1551278728748-1:1:1:1, destination = queue://amqp://localhost:61616, transactionId = null, expiration = 0, timestamp = 1551278728975, arrival = 0, brokerInTime = 1551278728977, brokerOutTime = 1551278729033, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = null, dataStructure = null, redeliveryCounter = 0, size = 0, properties = null, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false, text = Hello A-MQ 6}
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.903 s - in org.jboss.fuse.quickstarts.persistence.standalone.StandaloneAMQ6AccessTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.086 s
[INFO] Finished at: 2019-02-27T15:45:29+01:00
[INFO] ------------------------------------------------------------------------
----

== JavaEE example

`javaee-xa` is not OSGi related, but presents _canonical_ example of using JTA and JDBC APIs inside standard Servlet.
This example requires configuration of sample data sources inside Red Hat EAP server. The configuration details
are not presented in this quickstarts - only the API usage is shown.

== Camel JDBC example

`camel-jdbc` is a simple Camel context with routes that interact with camel-jdbc component. It is required
to configure docker-based PostgreSQL database (as presented in Persistence Manual).

Using fresh {f7} instance, we can (after building the example):
[listing,options="nowrap"]
----
karaf@root()> install -s mvn:org.postgresql/postgresql/42.2.5
Bundle ID: 227
karaf@root()> feature:install jdbc pax-jdbc-pool-dbcp2

karaf@root()> install -s mvn:org.jboss.fuse.quickstarts/camel-jdbc/${project.version}
Bundle ID: 238
----

After installing the example, we'll see this log output every 20 seconds:

[listing,options="nowrap"]
----
2019-02-27 16:13:09,834 INFO  {Camel (camel) thread #11 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=1, date=2018-02-20 08:00:00.0, name=User 1, summary=Incident 1, details=This is a report incident 001, email=user1@redhat.com}
2019-02-27 16:13:09,834 INFO  {Camel (camel) thread #11 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=2, date=2018-02-20 08:10:00.0, name=User 2, summary=Incident 2, details=This is a report incident 002, email=user2@redhat.com}
2019-02-27 16:13:09,834 INFO  {Camel (camel) thread #11 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=3, date=2018-02-20 08:20:00.0, name=User 3, summary=Incident 3, details=This is a report incident 003, email=user3@redhat.com}
2019-02-27 16:13:09,835 INFO  {Camel (camel) thread #11 - timer://webinar} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : *** Select all : {id=4, date=2018-02-20 08:30:00.0, name=User 4, summary=Incident 4, details=This is a report incident 004, email=user4@redhat.com}
----

Additionally, if a file will be created in `$FUSE_HOME/data/camel-jdbc`, additional query will be performed:
[listing,options="nowrap"]
----
$ echo -n '1,3' > data/camel-jdbc/query1.txt
----

After triggering `key-from-file` route using the above command, we'll see this in the log:
[listing,options="nowrap"]
----
2019-02-27 16:13:37,866 INFO  {Camel (camel) thread #10 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> SQL Query : select * from report.incident where id = '1'
2019-02-27 16:13:37,868 INFO  {Camel (camel) thread #10 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> Select using key : [{id=1, date=2018-02-20 08:00:00.0, name=User 1, summary=Incident 1, details=This is a report incident 001, email=user1@redhat.com}]
2019-02-27 16:13:37,868 INFO  {Camel (camel) thread #10 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> SQL Query : select * from report.incident where id = '3'
2019-02-27 16:13:37,871 INFO  {Camel (camel) thread #10 - file://data/camel-jdbc} [org.apache.camel.util.CamelLogger.log()] (CamelLogger.java:159) : >>> Select using key : [{id=3, date=2018-02-20 08:20:00.0, name=User 3, summary=Incident 3, details=This is a report incident 003, email=user3@redhat.com}]
----

== Camel XA example

`camel-xa` is a Camel context with routes that us multiple XA resources - two Artemis JMS queues and PostgreSQL database.
The database access is performed using JPA. It is required to configure docker-based PostgreSQL database (as presented
in Persistence Manual) and Artemis broker accessible at `tcp://localhost:61616` URL.

.Database
* user: `fuse`
* password: `fuse`
* database name: `reportdb`
* URI: `jdbc:postgresql://localhost:5432/reportdb`

.Broker
* user: `fuse`
* password: `fuse`
* URI: `tcp://localhost:61616`

Using fresh {f7} instance, we can (after building the example):
[listing,options="nowrap"]
----
karaf@root()> install -s mvn:org.postgresql/postgresql/42.2.5
Bundle ID: 224
karaf@root()> feature:install jdbc jms jndi
karaf@root()> feature:install pax-jdbc-pool-narayana pax-jms-pool-narayana pax-jms-artemis pax-jdbc-config pax-jms-config
karaf@root()> feature:install camel-blueprint camel-jpa camel-jms
karaf@root()> feature:install jpa hibernate-orm
----

Now we have to install blueprint-based datasource and connection factory. After replacing {f7} location for `$FUSE_HOME`
we can install file-based blueprints:

[listing,options="nowrap"]
----
karaf@root()> install -s blueprint:file://$FUSE_HOME/quickstarts/persistence/camel-xa/src/main/blueprint/connection-factory.xml
Bundle ID: 296
karaf@root()> install -s blueprint:file://$FUSE_HOME/quickstarts/persistence/camel-xa/src/main/blueprint/xa-datasource.xml
Bundle ID: 297
----

Install the example:
[listing,options="nowrap"]
----
karaf@root()> install -s mvn:org.jboss.fuse.quickstarts/camel-xa/${project.version}
Bundle ID: 298

karaf@root()> camel:route-list
 Context                     Route                   Status              Total #       Failed #     Inflight #   Uptime
 -------                     -----                   ------              -------       --------     ----------   ------
 xa-transaction-jms-ok-way   transactedTargetOkWay   Started                   0              0              0   4 minutes
----

We can test the route now:
[listing,options="nowrap"]
----
karaf@root()> jms:browse -u fuse -p fuse jms/artemisXAConnectionFactory xa1Queue
Message ID │ Content │ Charset │ Type │ Correlation ID │ Delivery Mode │ Destination │ Expiration │ Priority │ Redelivered │ ReplyTo │ Timestamp
───────────┼─────────┼─────────┼──────┼────────────────┼───────────────┼─────────────┼────────────┼──────────┼─────────────┼─────────┼──────────

karaf@root()> jms:browse -u fuse -p fuse jms/artemisXAConnectionFactory xa2Queue
Message ID │ Content │ Charset │ Type │ Correlation ID │ Delivery Mode │ Destination │ Expiration │ Priority │ Redelivered │ ReplyTo │ Timestamp
───────────┼─────────┼─────────┼──────┼────────────────┼───────────────┼─────────────┼────────────┼──────────┼─────────────┼─────────┼──────────

karaf@root()> jdbc:query jdbc/postgresDS 'select * from message'
messagetext
───────────

karaf@root()> jms:send -u fuse -p fuse jms/artemisXAConnectionFactory xa1Queue "Hello Camel XA"

karaf@root()> jdbc:query jdbc/postgresDS 'select * from message'
messagetext
──────────────
Hello Camel XA

karaf@root()> jms:browse -u fuse -p fuse jms/artemisXAConnectionFactory xa1Queue
Message ID │ Content │ Charset │ Type │ Correlation ID │ Delivery Mode │ Destination │ Expiration │ Priority │ Redelivered │ ReplyTo │ Timestamp
───────────┼─────────┼─────────┼──────┼────────────────┼───────────────┼─────────────┼────────────┼──────────┼─────────────┼─────────┼──────────

karaf@root()> jms:browse -u fuse -p fuse jms/artemisXAConnectionFactory xa2Queue
Message ID                              │ Content        │ Charset │ Type │ Correlation ID │ Delivery Mode │ Destination             │ Expiration │ Priority │ Redelivered │ ReplyTo │ Timestamp
────────────────────────────────────────┼────────────────┼─────────┼──────┼────────────────┼───────────────┼─────────────────────────┼────────────┼──────────┼─────────────┼─────────┼─────────────────────────────
ID:1b831abb-3b2b-11e9-8756-54e1ad3055fb │ Hello Camel XA │ UTF-8   │      │                │ Persistent    │ ActiveMQQueue[xa2Queue] │ Never      │ 4        │ false       │         │ Thu Feb 28 08:33:14 CET 2019

karaf@root()> camel:route-list
 Context                     Route                   Status              Total #       Failed #     Inflight #   Uptime
 -------                     -----                   ------              -------       --------     ----------   ------
 xa-transaction-jms-ok-way   transactedTargetOkWay   Started                   1              0              0   12 minutes
----
