= Database configuration

Before deploying/configuring anything in {f7} we need actual RDBMS system running.

Persistence quickstarts include SQL script that prepare database structures.

We will refer to the root directory of persistence quickstarts as `$PQ_HOME`. This directory is stored inside {f7}
installation in `$FUSE_HOME/quickstarts/persistence`.

== Container based PostgreSQL installation

We can use *official* PostgreSQL image available at https://hub.docker.com/_/postgres/[docker hub].
Any method of accessing PostgreSQL server may be used (e.g., mapping ports or connecting to container's IP address directly).

. Start PostgreSQL 13.4 server container:
+
[listing,options="nowrap"]
----
$ podman run -d --name fuse-postgresql-server -e POSTGRES_USER=fuse -e POSTGRES_PASSWORD=fuse -p 5432:5432 postgres:13.4
Trying to pull docker.io/library/postgres:13.4...
Getting image source signatures
...
Writing manifest to image destination
Storing signatures
5ab9fecc3bc4f163f5dd8eb5350d567a5e98742aba2160c3bf43a67052531fcb

$ podman ps
CONTAINER ID  IMAGE                            COMMAND     CREATED         STATUS             PORTS                   NAMES
5ab9fecc3bc4  docker.io/library/postgres:13.4  postgres    20 seconds ago  Up 20 seconds ago  0.0.0.0:5432->5432/tcp  fuse-postgresql-server
----

. Create `reportdb` database from the `fuse-postgresql-server` container:
+
[listing,options="nowrap"]
----
$ podman exec -ti fuse-postgresql-server /bin/bash
root@5ab9fecc3bc4:/# psql -U fuse -d fuse
psql (13.4 (Debian 13.4-4.pgdg110+1))
Type "help" for help.

fuse=# create database reportdb owner fuse encoding 'utf8';
CREATE DATABASE
fuse=# \c reportdb
You are now connected to database "reportdb" as user "fuse".
reportdb=# \q
root@5ab9fecc3bc4:/# exit
exit
----

. Initialize database by creating schema, table and populating the table with data:
+
[listing,options="nowrap"]
----
$ cd $PQ_HOME/databases/scripts
$ podman cp reportdb-postgresql-script.sql fuse-postgresql-server:/tmp
$ podman exec -ti fuse-postgresql-server /bin/bash
root@5ab9fecc3bc4:/# psql -U fuse -d reportdb -f /tmp/reportdb-postgresql-script.sql
psql:/tmp/reportdb-postgresql-script.sql:17: NOTICE:  schema "report" does not exist, skipping
DROP SCHEMA
CREATE SCHEMA
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
root@5ab9fecc3bc4:/# psql -U fuse -d reportdb
psql (13.4 (Debian 13.4-4.pgdg110+1))
Type "help" for help.

reportdb=# \c reportdb
You are now connected to database "reportdb" as user "fuse".
reportdb=# set schema 'report';
SET
reportdb=# \dt
         List of relations
 Schema |   Name   | Type  | Owner
--------+----------+-------+-------
 report | incident | table | fuse
(1 row)

reportdb=# select * from incident;
 id |        date         |  name  |  summary   |            details            |      email
----+---------------------+--------+------------+-------------------------------+------------------
  1 | 2018-02-20 08:00:00 | User 1 | Incident 1 | This is a report incident 001 | user1@redhat.com
  2 | 2018-02-20 08:10:00 | User 2 | Incident 2 | This is a report incident 002 | user2@redhat.com
  3 | 2018-02-20 08:20:00 | User 3 | Incident 3 | This is a report incident 003 | user3@redhat.com
  4 | 2018-02-20 08:30:00 | User 4 | Incident 4 | This is a report incident 004 | user4@redhat.com
(4 rows)

reportdb=# \q
root@5ab9fecc3bc4:/# exit
exit
----

. Configure PostgreSQL database to allow XA transactions:
+
We have to set `max_prepared_transactions` to the value equal or greater than `max_connections` setting
(`100` in the case of `postgres:13.4` image).
+
[listing,options="nowrap"]
----
$ podman exec -ti fuse-postgresql-server /bin/bash
root@5ab9fecc3bc4:/# grep max_prepared_transactions /var/lib/postgresql/data/postgresql.conf
#max_prepared_transactions = 0		# zero disables the feature
# Caution: it is not advisable to set max_prepared_transactions nonzero unless
root@5ab9fecc3bc4:/# sed -i 's/^#max_prepared_transactions = 0/max_prepared_transactions = 200/' /var/lib/postgresql/data/postgresql.conf
root@37536acdaee5:/# grep max_prepared_transactions /var/lib/postgresql/data/postgresql.conf
max_prepared_transactions = 200		# zero disables the feature
# Caution: it is not advisable to set max_prepared_transactions nonzero unless
root@5ab9fecc3bc4:/# exit
exit
----

. Restart `fuse-postgresql-server` container:
+
[listing,options="nowrap"]
----
$ podman stop fuse-postgresql-server
fuse-postgresql-server

$ podman start fuse-postgresql-server
fuse-postgresql-server
----
+
Your PostgreSQL 13.4 database is ready to use.

== Container based MariaDB installation

Docker image is available at https://hub.docker.com/_/mariadb/[docker hub].

. Start MariaDB 10.6.4 server container:
+
[listing,options="nowrap"]
----
$ podman run -d --name fuse-mariadb-server -e MYSQL_ROOT_PASSWORD=fuse -p 3306:3306 mariadb:10.6.4
Trying to pull docker.io/library/mariadb:10.6.4...
Getting image source signatures
...
Writing manifest to image destination
Storing signatures
666dd2909f4787a8f7ab8160ad97cdc90b6926d3e75e8cf08271774a08f9f685

$ podman ps
CONTAINER ID  IMAGE                             COMMAND     CREATED         STATUS             PORTS                   NAMES
666dd2909f47  docker.io/library/mariadb:10.6.4  mysqld      16 seconds ago  Up 16 seconds ago  0.0.0.0:3306->3306/tcp  fuse-mariadb-server
----

. Create `reportdb` database from the `fuse-mariadb-server` container:
+
[listing,options="nowrap"]
----
$ podman exec -ti fuse-mariadb-server /bin/bash
root@666dd2909f47:/# mysql -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.6.4-MariaDB-1:10.6.4+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> create database reportdb character set 'utf8';
Query OK, 1 row affected (0.000 sec)

MariaDB [(none)]> select password('fuse');
+-------------------------------------------+
| password('fuse')                          |
+-------------------------------------------+
| *66366D5297921E017C7C9378931FD111B3951D84 |
+-------------------------------------------+
1 row in set (0.000 sec)

MariaDB [(none)]> create user 'fuse'@'%' identified by password '*66366D5297921E017C7C9378931FD111B3951D84';
Query OK, 0 rows affected (0.003 sec)

MariaDB [(none)]> select Host, User, authentication_string, plugin from mysql.user;
+-----------+-------------+-------------------------------------------+-----------------------+
| Host      | User        | authentication_string                     | plugin                |
+-----------+-------------+-------------------------------------------+-----------------------+
| localhost | mariadb.sys |                                           | mysql_native_password |
| localhost | root        | *66366D5297921E017C7C9378931FD111B3951D84 | mysql_native_password |
| %         | root        | *66366D5297921E017C7C9378931FD111B3951D84 | mysql_native_password |
| %         | fuse        | *66366D5297921E017C7C9378931FD111B3951D84 | mysql_native_password |
+-----------+-------------+-------------------------------------------+-----------------------+
4 rows in set (0.001 sec)

MariaDB [(none)]> grant all on reportdb.* to 'fuse'@'%';
Query OK, 0 rows affected (0.052 sec)

MariaDB [(none)]> flush privileges;
Query OK, 0 rows affected (0.000 sec)

MariaDB [(none)]> \q
Bye
root@666dd2909f47:/# exit
exit
----

. Initialize database by creating table and populating the table with data:
+
[listing,options="nowrap"]
----
$ cd $PQ_HOME/databases/scripts
$ podman cp reportdb-mariadb-script.sql fuse-mariadb-server:/tmp
$ podman exec -ti fuse-mariadb-server /bin/bash
root@666dd2909f47:/# mysql -u fuse reportdb -p < /tmp/reportdb-mariadb-script.sql
Enter password:
root@666dd2909f47:/# mysql -u fuse -p reportdb
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 5
Server version: 10.6.4-MariaDB-1:10.6.4+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [reportdb]> show tables;
+--------------------+
| Tables_in_reportdb |
+--------------------+
| incident           |
+--------------------+
1 row in set (0.000 sec)

MariaDB [reportdb]> desc incident;
+---------+--------------+------+-----+---------------------+-------------------------------+
| Field   | Type         | Null | Key | Default             | Extra                         |
+---------+--------------+------+-----+---------------------+-------------------------------+
| id      | int(11)      | NO   | PRI | NULL                | auto_increment                |
| date    | timestamp    | NO   |     | current_timestamp() | on update current_timestamp() |
| name    | varchar(35)  | YES  |     | NULL                |                               |
| summary | varchar(35)  | YES  |     | NULL                |                               |
| details | varchar(255) | YES  |     | NULL                |                               |
| email   | varchar(60)  | YES  |     | NULL                |                               |
+---------+--------------+------+-----+---------------------+-------------------------------+
6 rows in set (0.001 sec)

MariaDB [reportdb]> select * from incident;
+----+---------------------+--------+------------+-------------------------------+------------------+
| id | date                | name   | summary    | details                       | email            |
+----+---------------------+--------+------------+-------------------------------+------------------+
|  1 | 2018-02-20 08:00:00 | User 1 | Incident 1 | This is a report incident 001 | user1@redhat.com |
|  2 | 2018-02-20 08:10:00 | User 2 | Incident 2 | This is a report incident 002 | user2@redhat.com |
|  3 | 2018-02-20 08:20:00 | User 3 | Incident 3 | This is a report incident 003 | user3@redhat.com |
|  4 | 2018-02-20 08:30:00 | User 4 | Incident 4 | This is a report incident 004 | user4@redhat.com |
+----+---------------------+--------+------------+-------------------------------+------------------+
4 rows in set (0.000 sec)

MariaDB [reportdb]> \q
Bye
root@666dd2909f47:/# exit
exit
----

+
Your MariaDB 10.6.4 database is ready to use.

=== Container based MySQL installation

Docker image is available at https://hub.docker.com/_/mysql/[docker hub].

. Start MySQL 8.0.26 server container:
+
[listing,options="nowrap"]
----
$ podman run -d --name fuse-mysql-server -e MYSQL_ROOT_PASSWORD=fuse -p 3306:3306 mysql:8.0.26
Trying to pull docker.io/library/mysql:8.0.26...
Getting image source signatures
...
Writing manifest to image destination
Storing signatures
6cc00f3c04ad3a80d82e9750a6e0b039259bd5a41814a3cc4be5b9faa71f2cbe
----

. Create `reportdb` database from the `fuse-mysql-server` container:
+
[listing,options="nowrap"]
----
$ podman exec -ti fuse-mysql-server /bin/bash
root@6cc00f3c04ad:/# mysql -p mysql
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
root@6cc00f3c04ad:/# mysql -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.26 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database reportdb character set 'utf8';
Query OK, 1 row affected, 1 warning (0.05 sec)

mysql> create user 'fuse'@'%' identified with mysql_native_password by 'fuse';
Query OK, 0 rows affected (0.04 sec)

mysql> grant all on reportdb.* to 'fuse'@'%';
Query OK, 0 rows affected (0.03 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)

mysql> \q
Bye
root@6cc00f3c04ad:/# exit
exit
----

. Initialize database by creating table and populating the table with data (same script as for MariaDB):
+
[listing,options="nowrap"]
----
$ cd $PQ_HOME/databases/scripts
$ podman cp reportdb-mariadb-script.sql fuse-mysql-server:/tmp/reportdb-mysql-script.sql
$ podman exec -ti fuse-mysql-server /bin/bash
root@6cc00f3c04ad:/# mysql -u fuse reportdb -p < /tmp/reportdb-mysql-script.sql
Enter password:
root@6cc00f3c04ad:/# mysql -u fuse -p reportdb
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.0.26 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show tables;
+--------------------+
| Tables_in_reportdb |
+--------------------+
| incident           |
+--------------------+
1 row in set (0.01 sec)

mysql> desc incident;
+---------+--------------+------+-----+---------+----------------+
| Field   | Type         | Null | Key | Default | Extra          |
+---------+--------------+------+-----+---------+----------------+
| id      | int          | NO   | PRI | NULL    | auto_increment |
| date    | timestamp    | YES  |     | NULL    |                |
| name    | varchar(35)  | YES  |     | NULL    |                |
| summary | varchar(35)  | YES  |     | NULL    |                |
| details | varchar(255) | YES  |     | NULL    |                |
| email   | varchar(60)  | YES  |     | NULL    |                |
+---------+--------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

mysql> select * from incident;
+----+---------------------+--------+------------+-------------------------------+------------------+
| id | date                | name   | summary    | details                       | email            |
+----+---------------------+--------+------------+-------------------------------+------------------+
|  1 | 2018-02-20 08:00:00 | User 1 | Incident 1 | This is a report incident 001 | user1@redhat.com |
|  2 | 2018-02-20 08:10:00 | User 2 | Incident 2 | This is a report incident 002 | user2@redhat.com |
|  3 | 2018-02-20 08:20:00 | User 3 | Incident 3 | This is a report incident 003 | user3@redhat.com |
|  4 | 2018-02-20 08:30:00 | User 4 | Incident 4 | This is a report incident 004 | user4@redhat.com |
+----+---------------------+--------+------------+-------------------------------+------------------+
4 rows in set (0.00 sec)

mysql> \q
Bye
root@6cc00f3c04ad:/# exit
exit
----

+
Your MySQL 8.0.26 database is ready to use.

== Embedded Derby database

There's no need to configure anything. Derby database will run in in-memory using `jdbc:derby:reportdb;create=true`
JDBC URL. The table will be created directly from Java™ code.
