= Message Broker configuration

In this chapter we'll configure testing message brokers.

We'll be testing:

* A-MQ 6
* A-MQ 7 (Artemis)
* IBM MQ 8
* IBM MQ 9

[[ibm-mq]]
== Container based IBM MQ 9 installation

We can use *official* image available at https://hub.docker.com/r/ibmcom/mq/[docker hub].
The sources for Dockerfile are stored in https://github.com/ibm-messaging/mq-docker[github project].

. Start IBM MQ 9 docker container (9.1.5.0-r1 doesn't work: https://github.com/ibm-messaging/mq-container/issues/400):
+
[listing,options="nowrap"]
----
$ podman run -d --name fuse-webspheremq9 --env LICENSE=accept --env MQ_QMGR_NAME=FUSEQM --publish 1414:1414 --publish 19443:9443 ibmcom/mq:9.1.3.0
Trying to pull docker.io/ibmcom/mq:9.1.3.0...
Getting image source signatures
...
Storing signatures
1e397bb7318d027e27be7c2ad02eeee6c0c61ea7fb069071dcda51747fadf6f8

 podman ps
CONTAINER ID  IMAGE                            COMMAND   CREATED         STATUS             PORTS                                            NAMES
1e397bb7318d  docker.io/ibmcom/mq:9.1.3.0                9 seconds ago   Up 10 seconds ago  0.0.0.0:1414->1414/tcp, 0.0.0.0:19443->9443/tcp  fuse-webspheremq9
----

. Check if web console works
+
With the above port mapping, we can access web console at https://localhost:19443/ibmmq/console/ using
`admin`/`passw0rd` credentials (see details https://github.com/ibm-messaging/mq-docker#web-console[here]).

. Check if MQ Explorer works
+
We can install IBM MQ Explorer downloaded from https://developer.ibm.com/messaging/mq-downloads/ (check _MQ Explorer standalone download_ link).
+
After installing IBM MQ Explorer, we can add broker connection with these properties:

* _Queue manager name_: `FUSEQM`, _connect directly_
* _Host name or IP address_: `localhost`
* _Server connection channel_: `DEV.ADMIN.SVRCONN`
* Check _Enable user identification_ and use user: `admin`, password: `passw0rd`.

+
Then, under _Queues_ node we should see `DEV.QUEUE.[1-3]` and `DEV.DEAD.LETTER.QUEUE`.

=== Authentication configuration

In order to test the examples, we have to configure proper channel security. https://github.com/ibm-messaging/mq-docker#running-mq-commands[github page]
points us to https://www.ibm.com/developerworks/community/blogs/messaging/entry/getting_going_without_turning_off_mq_security?lang=en[article about security configuration].
There's also another article https://www.ibm.com/developerworks/community/blogs/aimsupport/entry/chlauth_allow_some_privileged_admins?lang=en[here].

We need to override security configuration for `DEV.APP.SVRCONN` channel which we'll use for client connections.

.Connect to docker container and run `runmqsc` command as `mqm` user:
[listing,options="nowrap"]
----
$ podman exec -ti fuse-webspheremq9 /bin/bash

bash-4.2$ id
uid=888(mqm) gid=888(mqm) groups=888(mqm)

bash-4.2$ runmqsc
5724-H72 (C) Copyright IBM Corp. 1994, 2019.
Starting MQSC for queue manager FUSEQM.
----

.Check current configuration of the channel
[listing,options="nowrap"]
----
display channel (DEV.APP.SVRCONN)
     1 : display channel (DEV.APP.SVRCONN)
AMQ8414I: Display Channel details.
   CHANNEL(DEV.APP.SVRCONN)                CHLTYPE(SVRCONN)
   ALTDATE(2021-03-31)                     ALTTIME(16.16.44)
   CERTLABL( )                             COMPHDR(NONE)
   COMPMSG(NONE)                           DESCR( )
   DISCINT(0)                              HBINT(300)
   KAINT(AUTO)                             MAXINST(999999999)
   MAXINSTC(999999999)                     MAXMSGL(4194304)
   MCAUSER(app)                            MONCHL(QMGR)
   RCVDATA( )                              RCVEXIT( )
   SCYDATA( )                              SCYEXIT( )
   SENDDATA( )                             SENDEXIT( )
   SHARECNV(10)                            SSLCAUTH(REQUIRED)
   SSLCIPH( )                              SSLPEER( )
   TRPTYPE(TCP)

display chlauth('*')
     2 : display chlauth('*')
...
AMQ8878I: Display channel authentication record details.
   CHLAUTH(DEV.APP.SVRCONN)                TYPE(ADDRESSMAP)
   ADDRESS(*)                              USERSRC(CHANNEL)
...
MQ8878I: Display channel authentication record details.
   CHLAUTH(*)                              TYPE(ADDRESSMAP)
   ADDRESS(*)                              USERSRC(NOACCESS)
AMQ8878I: Display channel authentication record details.
   CHLAUTH(*)                              TYPE(BLOCKUSER)
   USERLIST(*MQADMIN)
----

Default auth configuration blocks authenticated users by default.

.Override blocking by specifying different list of blocked users
[listing,options="nowrap"]
----
SET CHLAUTH(DEV.APP.SVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') DESCR('Allow privileged users on this channel')
     3 : SET CHLAUTH(DEV.APP.SVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') DESCR('Allow privileged users on this channel')
AMQ8877I: IBM MQ channel authentication record set.
----

.Enable client connection on `DEV.APP.SVRCONN` channel
[listing,options="nowrap"]
----
SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('BackStop rule')
     4 : SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('BackStop rule')
AMQ8883E: Channel authentication record already exists.

SET CHLAUTH(DEV.APP.SVRCONN) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
     5 : SET CHLAUTH(DEV.APP.SVRCONN) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
AMQ8883E: Channel authentication record already exists.
----

.Enable password authentication (instead of _runas_ authentication)
[listing,options="nowrap"]
----
ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
     6 : ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
AMQ8567I: IBM MQ authentication information changed.

REFRESH SECURITY TYPE(CONNAUTH)
     7 : REFRESH SECURITY TYPE(CONNAUTH)
AMQ8560I: IBM MQ security cache refreshed.

exit
     8 : exit
7 MQSC commands read.
No commands have a syntax error.
2 valid MQSC commands could not be processed.
----

.Change password of `app` user
After exiting `runmqsc` we have to use the only allowed (in `/etc/sudoers.d/mq-dev-config`) command to change the password of `app` user (hit `CTRL-D` after specifying `app:fuse`):
[listing,options="nowrap"]
----
bash-4.2$ id
uid=888(mqm) gid=888(mqm) groups=888(mqm)

bash-4.2$ sudo /usr/sbin/chpasswd
app:fuse
^D

bash-4.2$ su - app
Password: fuse
[app@1e397bb7318d ~]$ id
uid=1001(app) gid=1002(app) groups=1002(app),1001(mqclient)
----

[[ibmmq-client-libraries]]
=== Client libraries

For completeness, here's the list of libraries that should be used with IBM MQ 9.

IMPORTANT: The examples refer to version 9.1.0.7 of IBM MQ Client libraries, but please consult official documentation for supported version of the libraries.

If we go to https://www.ibm.com/support/pages/mqc91-ibm-mq-clients,
we can download `IBM MQ 9.1.0.7 LTS Clients` package. The links may vary, but I was able to download version 9.1.0.7 after clicking https://ibm.biz/ibm-mq-clients-all-lts_91 link and manipulating search criteria.

To be precise, here are the checksums:

[listing,options="nowrap"]
----
$ sha1sum 9.1.0.7-IBM*
8d8933b5d871ea64467eb9d25873c073200923de  9.1.0.7-IBM-MQC-Redist-Java.zip
ec376298c55ddc53aa05c5056bd0bf241dd7e6a7  9.1.0.7-IBM-MQ-Install-Java-All.jar
----

`9.1.0.7-IBM-MQ-Install-Java-All` package contains three subdirectories in this package:

* `wmq/JavaEE` contains resource adapter archive (`wmq.jmsra.rar`)
* `wmq/JavaSE` contains `com.ibm.mq.allclient.jar` library and dependencies
* `wmq/OSGi` contains respective `com.ibm.mq.osgi.allclient_9.1.0.7.jar` and dependencies

IMPORTANT: This quickstarts manual is not a definitive guide about which IBM MQ access methods are the canonical ones.

== A-MQ 7 installation (Artemis)

This time we'll run standalone (no docker) version of `amq-broker-7.8.1-bin.zip`.

[listing,options="nowrap"]
----
$ pwd
/data/servers/amq-broker-7.8.1

$ bin/artemis create --user fuse --password fuse --require-login amq7
Creating ActiveMQ Artemis instance at: /data/servers/amq-broker-7.8.1/amq7

Auto tuning journal ...
done! Your system can make 31.25 writes per millisecond, your journal-buffer-timeout will be 32000

You can now start the broker by executing:

   "/data/servers/amq-broker-7.8.1/amq7/bin/artemis" run

Or you can run the broker in the background using:

   "/data/servers/amq-broker-7.8.1/amq7/bin/artemis-service" start


$ amq7/bin/artemis run
           __  __  ____    ____            _
     /\   |  \/  |/ __ \  |  _ \          | |
    /  \  | \  / | |  | | | |_) |_ __ ___ | | _____ _ __
   / /\ \ | |\/| | |  | | |  _ <| '__/ _ \| |/ / _ \ '__|
  / ____ \| |  | | |__| | | |_) | | | (_) |   <  __/ |
 /_/    \_\_|  |_|\___\_\ |____/|_|  \___/|_|\_\___|_|

 Red Hat AMQ 7.8.1.GA


2021-03-31 18:30:00,353 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
...
----

=== Client libraries

Artemis libraries are available in Maven Central or Red Hat repository. I used:

* `mvn:org.apache.activemq/artemis-core-client/2.16.0.redhat-00012`
* `mvn:org.apache.activemq/artemis-jms-client/2.16.0.redhat-00012`

== A-MQ 6 installation

For A-MQ 6 we'll run standalone (no docker) version of `jboss-a-mq-6.3.0.redhat-495.zip`.

.Add authentication entries

We'll add two authentication entries to `etc/users.properties`:
[listing,options="nowrap"]
----
admin=admin,admin,manager,viewer,Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser
fuse=fuse,Operator
----

.Run A-MQ 6
[listing,options="nowrap"]
----
$ pwd
/data/servers/jboss-a-mq-6.3.0.redhat-495

$ bin/amq
Please wait, JBoss A-MQ is initializing...
100% [========================================================================]

      _ ____                                __  __  ____
     | |  _ \                    /\        |  \/  |/ __ \
     | | |_) | ___  ___ ___     /  \ ______| \  / | |  | |
 _   | |  _ < / _ \/ __/ __|   / /\ \______| |\/| | |  | |
| |__| | |_) | (_) \__ \__ \  / ____ \     | |  | | |__| |
 \____/|____/ \___/|___/___/ /_/    \_\    |_|  |_|\___\_\

  JBoss A-MQ (6.3.0.redhat-495)
  http://www.redhat.com/products/jbossenterprisemiddleware/amq/

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.

Open a browser to http://localhost:8181 to access the management console

Hit '<ctrl-d>' or 'osgi:shutdown' to shutdown JBoss A-MQ.

JBossA-MQ:karaf@root> bstat
connectorName = ws

connectorName = openwire


BrokerName = amq
TotalEnqueueCount = 1
TotalDequeueCount = 0
TotalMessageCount = 0
TotalConsumerCount = 0
Uptime = 1.360 seconds

Name = KahaDBPersistenceAdapter[/data/servers/jboss-a-mq-6.3.0.redhat-495/data/amq/kahadb,Index:/data/servers/jboss-a-mq-6.3.0.redhat-495/data/amq/kahadb]

connectorName = amqp

connectorName = mqtt
----

=== Client libraries

Libraries are available in Maven Central or Red Hat repository. I used:

* `mvn:org.apache.activemq/activemq-client/5.11.0.redhat-630495`
