= Message Broker configuration

In this chapter we'll configure testing message brokers.

We'll be testing:

* A-MQ 6
* A-MQ 7 (Artemis)
* IBM MQ 8
* IBM MQ 9

[[ibm-mq]]
== Container based IBM MQ 9 installation

We can use *official* image available at https://hub.docker.com/r/ibmcom/mq/[docker hub].
The sources for Dockerfile are stored in https://github.com/ibm-messaging/mq-docker[github project].

. Start IBM MQ 9 docker container (9.1.5.0-r1 doesn't work: https://github.com/ibm-messaging/mq-container/issues/400):
+
[listing,options="nowrap"]
----
$ podman run -d --name fuse-webspheremq9 --env LICENSE=accept --env MQ_QMGR_NAME=FUSEQM --env MQ_APP_PASSWORD=fuse --publish 1414:1414 --publish 19443:9443 ibmcom/mq:9.2.3.0-r1
Trying to pull docker.io/ibmcom/mq:9.1.3.0...
Getting image source signatures
...
Storing signatures
9365e6a57097a461007ee1740f950c574ab6300f2a83ecf5c9c4e6ed4611ff64

$ podman ps
CONTAINER ID  IMAGE                           COMMAND     CREATED        STATUS            PORTS                                            NAMES
9365e6a57097  docker.io/ibmcom/mq:9.2.3.0-r1              6 seconds ago  Up 6 seconds ago  0.0.0.0:1414->1414/tcp, 0.0.0.0:19443->9443/tcp  fuse-webspheremq9
----

. Check if web console works
+
With the above port mapping, we can access web console at https://localhost:19443/ibmmq/console/ using
`admin`/`passw0rd` credentials (see details https://github.com/ibm-messaging/mq-docker#web-console[here]).

. Check if MQ Explorer works
+
We can install IBM MQ Explorer downloaded from https://developer.ibm.com/messaging/mq-downloads/ (check _MQ Explorer standalone download_ link).
+
After installing IBM MQ Explorer, we can add broker connection with these properties:

* _Queue manager name_: `FUSEQM`, _connect directly_
* _Host name or IP address_: `localhost`
* _Server connection channel_: `DEV.ADMIN.SVRCONN`
* Check _Enable user identification_ and use user: `admin`, password: `passw0rd`.

+
Then, under _Queues_ node we should see `DEV.QUEUE.[1-3]` and `DEV.DEAD.LETTER.QUEUE`.

=== Authentication configuration

In order to test the examples, we have to configure proper channel security. https://github.com/ibm-messaging/mq-docker#running-mq-commands[github page]
points us to https://www.ibm.com/developerworks/community/blogs/messaging/entry/getting_going_without_turning_off_mq_security?lang=en[article about security configuration].
There's also another article https://www.ibm.com/developerworks/community/blogs/aimsupport/entry/chlauth_allow_some_privileged_admins?lang=en[here].

Using `MQ_APP_PASSWORD` environment variable, we've specified the password for `app` user. It is required now when connecting to IBM MQ Broker.

[[ibmmq-client-libraries]]
=== Client libraries

For completeness, here's the list of libraries that should be used with IBM MQ 9.

IMPORTANT: The examples refer to version 9.1.0.7 of IBM MQ Client libraries, but please consult official documentation for supported version of the libraries.

If we go to https://www.ibm.com/support/pages/mqc91-ibm-mq-clients,
we can download `IBM MQ 9.1.0.7 LTS Clients` package. The links may vary, but I was able to download version 9.1.0.7 after clicking https://ibm.biz/ibm-mq-clients-all-lts_91 link and manipulating search criteria.

To be precise, here are the checksums:

[listing,options="nowrap"]
----
$ sha1sum 9.1.0.7-IBM*
8d8933b5d871ea64467eb9d25873c073200923de  9.1.0.7-IBM-MQC-Redist-Java.zip
ec376298c55ddc53aa05c5056bd0bf241dd7e6a7  9.1.0.7-IBM-MQ-Install-Java-All.jar
----

`9.1.0.7-IBM-MQ-Install-Java-All` package contains three subdirectories in this package:

* `wmq/JavaEE` contains resource adapter archive (`wmq.jmsra.rar`)
* `wmq/JavaSE` contains `com.ibm.mq.allclient.jar` library and dependencies
* `wmq/OSGi` contains respective `com.ibm.mq.osgi.allclient_9.1.0.7.jar` and dependencies

IMPORTANT: This quickstarts manual is not a definitive guide about which IBM MQ access methods are the canonical ones.

== A-MQ 7 installation (Artemis)

This time we'll run standalone (no docker) version of `amq-broker-7.8.1-bin.zip`.

[listing,options="nowrap"]
----
$ pwd
/data/servers/amq-broker-7.8.2

$ bin/artemis create --user fuse --password fuse --require-login amq7
Creating ActiveMQ Artemis instance at: /data/servers/amq-broker-7.8.2/amq7

Auto tuning journal ...
done! Your system can make 7.81 writes per millisecond, your journal-buffer-timeout will be 32000

You can now start the broker by executing:

   "/data/servers/amq-broker-7.8.2/amq7/bin/artemis" run

Or you can run the broker in the background using:

   "/data/servers/amq-broker-7.8.2/amq7/bin/artemis-service" start


$ amq7/bin/artemis run
           __  __  ____    ____            _
     /\   |  \/  |/ __ \  |  _ \          | |
    /  \  | \  / | |  | | | |_) |_ __ ___ | | _____ _ __
   / /\ \ | |\/| | |  | | |  _ <| '__/ _ \| |/ / _ \ '__|
  / ____ \| |  | | |__| | | |_) | | | (_) |   <  __/ |
 /_/    \_\_|  |_|\___\_\ |____/|_|  \___/|_|\_\___|_|

 Red Hat AMQ 7.8.2.GA


2021-10-04 16:20:21,244 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
...
----

=== Client libraries

Artemis libraries are available in Maven Central or Red Hat repository. I used:

* `mvn:org.apache.activemq/artemis-core-client/2.16.0.redhat-00022`
* `mvn:org.apache.activemq/artemis-jms-client/2.16.0.redhat-00022`

== A-MQ 6 installation

For A-MQ 6 we'll run standalone (no docker) version of `jboss-a-mq-6.3.0.redhat-495.zip`.

.Add authentication entries

We'll add two authentication entries to `etc/users.properties`:
[listing,options="nowrap"]
----
admin=admin,admin,manager,viewer,Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser
fuse=fuse,Operator
----

.Run A-MQ 6
[listing,options="nowrap"]
----
$ pwd
/data/servers/jboss-a-mq-6.3.0.redhat-495

$ bin/amq
Please wait, JBoss A-MQ is initializing...
100% [========================================================================]

      _ ____                                __  __  ____
     | |  _ \                    /\        |  \/  |/ __ \
     | | |_) | ___  ___ ___     /  \ ______| \  / | |  | |
 _   | |  _ < / _ \/ __/ __|   / /\ \______| |\/| | |  | |
| |__| | |_) | (_) \__ \__ \  / ____ \     | |  | | |__| |
 \____/|____/ \___/|___/___/ /_/    \_\    |_|  |_|\___\_\

  JBoss A-MQ (6.3.0.redhat-495)
  http://www.redhat.com/products/jbossenterprisemiddleware/amq/

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.

Open a browser to http://localhost:8181 to access the management console

Hit '<ctrl-d>' or 'osgi:shutdown' to shutdown JBoss A-MQ.

JBossA-MQ:karaf@root> bstat
connectorName = ws

connectorName = openwire


BrokerName = amq
TotalEnqueueCount = 1
TotalDequeueCount = 0
TotalMessageCount = 0
TotalConsumerCount = 0
Uptime = 7.391 seconds

Name = KahaDBPersistenceAdapter[/data/servers/jboss-a-mq-6.3.0.redhat-495/data/amq/kahadb,Index:/data/servers/jboss-a-mq-6.3.0.redhat-495/data/amq/kahadb]

connectorName = amqp

connectorName = mqtt
----

=== Client libraries

Libraries are available in Maven Central or Red Hat repository. I used:

* `mvn:org.apache.activemq/activemq-client/5.11.0.redhat-630495`
