= Message Broker configuration

In this chapter we'll configure testing message brokers.

We'll be testing:

* A-MQ 6
* A-MQ 7 (Artemis)
* IBM MQ 8
* IBM MQ 9

[[ibm-mq]]
== Container based IBM MQ 9 installation

We can use *official* image available at https://hub.docker.com/r/ibmcom/mq/[docker hub].
The sources for Dockerfile are stored in https://github.com/ibm-messaging/mq-docker[github project].

. Start IBM MQ 9 docker container:
+
[listing,options="nowrap"]
----
$ podman run -d --name fuse-webspheremq9 --env LICENSE=accept --env MQ_QMGR_NAME=FUSEQM --env MQ_APP_PASSWORD=fuse --publish 1414:1414 --publish 19443:9443 ibmcom/mq:9.2.4.0-r1
Trying to pull docker.io/ibmcom/mq:9.2.4.0-r1...
Getting image source signatures
...
Storing signatures
1deeb4cbeae17065ee44065d75a9d9c16b381b50302f8ddc622ece8e35e5bbd6

$ podman ps
CONTAINER ID  IMAGE                           COMMAND     CREATED         STATUS             PORTS                                            NAMES
1deeb4cbeae1  docker.io/ibmcom/mq:9.2.4.0-r1              23 seconds ago  Up 23 seconds ago  0.0.0.0:1414->1414/tcp, 0.0.0.0:19443->9443/tcp  fuse-webspheremq9
----

. Check if web console works
+
With the above port mapping, we can access web console at https://localhost:19443/ibmmq/console/ using
`admin`/`passw0rd` credentials (see details https://github.com/ibm-messaging/mq-docker#web-console[here]).

. Check if MQ Explorer works
+
We can install IBM MQ Explorer downloaded from https://ibm.biz/mqexplorer.
+
After installing IBM MQ Explorer, we can add broker connection with these properties:

* _Queue manager name_: `FUSEQM`, _connect directly_
* _Host name or IP address_: `localhost`
* _Server connection channel_: `DEV.ADMIN.SVRCONN`
* Check _Enable user identification_ and use user: `admin`, password: `passw0rd`.

+
Then, under _Queues_ node we should see `DEV.QUEUE.[1-3]` and `DEV.DEAD.LETTER.QUEUE`.

=== Authentication configuration

In order to test the examples, we have to configure proper channel security. https://github.com/ibm-messaging/mq-docker#running-mq-commands[github page]
points us to https://www.ibm.com/developerworks/community/blogs/messaging/entry/getting_going_without_turning_off_mq_security?lang=en[article about security configuration].
There's also another article https://www.ibm.com/developerworks/community/blogs/aimsupport/entry/chlauth_allow_some_privileged_admins?lang=en[here].

Using `MQ_APP_PASSWORD` environment variable, we've specified the password for `app` user. It is required now when connecting to IBM MQ Broker.

[[ibmmq-client-libraries]]
=== Client libraries

For completeness, here's the list of libraries that should be used with IBM MQ 9.

IMPORTANT: The examples refer to version 9.2.5.0 of IBM MQ Client libraries, but please consult official documentation for supported version of the libraries.

If we go to https://developer.ibm.com/articles/mq-downloads/#java,
we can click `https://ibm.biz/IBM-MQ-Install-Java-All` link, which redirects to proper download page. I've downloaded `9.2.5.0-IBM-MQ-Install-Java-All` package. The links may vary though....

To be precise, here are the checksums:

[listing,options="nowrap"]
----
$ md5sum 9.2.5.0-IBM-MQ*.*
ff47f87b09996c11ae2c53ac528c7bb0  9.2.5.0-IBM-MQC-Redist-Java.zip
d5152ce6970c21c07fc8c9a6701a438e  9.2.5.0-IBM-MQ-Install-Java-All.jar
----

`9.2.5.0-IBM-MQ-Install-Java-All` package contains three subdirectories in this package:

* `wmq/JavaEE` contains resource adapter archive (`wmq.jmsra.rar`)
* `wmq/JavaSE/lib` contains `com.ibm.mq.allclient.jar` library and dependencies
* `wmq/OSGi` contains respective `com.ibm.mq.osgi.allclient_9.2.5.0.jar` and dependencies

IMPORTANT: This quickstarts manual is not a definitive guide about which IBM MQ access methods are the canonical ones.

== A-MQ 7 installation (Artemis)

This time we'll run standalone (no docker) version of `amq-broker-7.8.4-bin.zip`.

[listing,options="nowrap"]
----
$ pwd
/data/servers/amq-broker-7.8.4

$ bin/artemis create --user fuse --password fuse --require-login amq7
Creating ActiveMQ Artemis instance at: /data/servers/amq-broker-7.8.2/amq7

Auto tuning journal ...
done! Your system can make 25 writes per millisecond, your journal-buffer-timeout will be 40000

You can now start the broker by executing:

   "/data/servers/amq-broker-7.8.4/amq7/bin/artemis" run

Or you can run the broker in the background using:

   "/data/servers/amq-broker-7.8.4/amq7/bin/artemis-service" start


$ amq7/bin/artemis run
           __  __  ____    ____            _
     /\   |  \/  |/ __ \  |  _ \          | |
    /  \  | \  / | |  | | | |_) |_ __ ___ | | _____ _ __
   / /\ \ | |\/| | |  | | |  _ <| '__/ _ \| |/ / _ \ '__|
  / ____ \| |  | | |__| | | |_) | | | (_) |   <  __/ |
 /_/    \_\_|  |_|\___\_\ |____/|_|  \___/|_|\_\___|_|

 Red Hat AMQ 7.8.4.GA


2022-03-14 12:19:02,505 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
...
----

=== Client libraries

Artemis libraries are available in Maven Central or Red Hat repository. I used:

* `mvn:org.apache.activemq/artemis-core-client/2.16.0.redhat-00036`
* `mvn:org.apache.activemq/artemis-jms-client/2.16.0.redhat-00036`

== A-MQ 6 installation

For A-MQ 6 we'll run standalone (no docker) version of `jboss-a-mq-6.3.0.redhat-516.zip`.

.Add authentication entries

We'll add two authentication entries to `etc/users.properties`:
[listing,options="nowrap"]
----
admin=admin,admin,manager,viewer,Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser
fuse=fuse,Operator
----

.Run A-MQ 6
[listing,options="nowrap"]
----
$ pwd
/data/servers/jboss-a-mq-6.3.0.redhat-516

$ bin/amq
Please wait, JBoss A-MQ is initializing...
100% [========================================================================]

      _ ____                                __  __  ____
     | |  _ \                    /\        |  \/  |/ __ \
     | | |_) | ___  ___ ___     /  \ ______| \  / | |  | |
 _   | |  _ < / _ \/ __/ __|   / /\ \______| |\/| | |  | |
| |__| | |_) | (_) \__ \__ \  / ____ \     | |  | | |__| |
 \____/|____/ \___/|___/___/ /_/    \_\    |_|  |_|\___\_\

  JBoss A-MQ (6.3.0.redhat-516)
  http://www.redhat.com/products/jbossenterprisemiddleware/amq/

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.

Open a browser to http://localhost:8181 to access the management console

Hit '<ctrl-d>' or 'osgi:shutdown' to shutdown JBoss A-MQ.

JBossA-MQ:karaf@root> bstat
connectorName = ws

connectorName = openwire


BrokerName = amq
TotalEnqueueCount = 1
TotalDequeueCount = 0
TotalMessageCount = 0
TotalConsumerCount = 0
Uptime = 13.228 seconds

Name = KahaDBPersistenceAdapter[/data/servers/jboss-a-mq-6.3.0.redhat-516/data/amq/kahadb,Index:/data/servers/jboss-a-mq-6.3.0.redhat-516/data/amq/kahadb]

connectorName = amqp

connectorName = mqtt
----

=== Client libraries

Libraries are available in Maven Central or Red Hat repository. I used:

* `mvn:org.apache.activemq/activemq-client/5.11.0.redhat-630516`
